version: '3'

services:
  web:
    build:
      context: .
    ports:
      - '3000:3000'
    command: npm start
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      - WATCHPACK_POLLING=true
